/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processors_ProcessorNative */

#ifndef _Included_processors_ProcessorNative
#define _Included_processors_ProcessorNative
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     processors_ProcessorNative
	 * Method:    convolve
	 * Signature: ([[D[[D)[[D
	 */
	JNIEXPORT jobjectArray JNICALL Java_processors_ProcessorNative_convolve
	(JNIEnv*, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif

